[tool.poetry]
name = "airfoil-database"
version = "0.0.1"
description = "Consistent B-spline representation for the UIUC airfoil database."
authors = ["Gabriel B. Santos <9348147+gabrielbdsantos@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
bs4 = "^0.0.1"
requests = "^2.26.0"
scipy = "^1.7"
numpy = "^1.21"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
